name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev
          wget https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_stable.tar.xz
          tar xf flutter_linux_stable.tar.xz
          export PATH=$PATH:`pwd`/flutter/bin

      - name: Run Flutter command
        run: |
          flutter pub get
          flutter test
